backend:
  name: github
  repo: masonrichter/dovetail-official
  branch: main

media_folder: "StaticWebsite/assets/images"
public_folder: "/StaticWebsite/assets/images"

collections:
  - name: "blog"
    label: "Blog"
    folder: "StaticWebsite/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
